### ISSUE TITLE
How to perform training with our own dataset 

### ISSUE THREAD

**Issue by angieAAAAA** [zhihao-lin/urbanir#1]
Thanks for your excellent work! Can you provide detailed instructions on how to run with our own images or videos?

**Comment by zhihao-lin** [comment]
Hi thanks for your interest in our project! In the readme we provide instruction under **Customized Data** section, and I also copy and paste here:
- The camera poses are estimated with [NeRFstudio pipeline](https://docs.nerf.studio/quickstart/custom_dataset.html) (transforms.json).
- The depth is estimated with [MiDaS](https://github.com/isl-org/MiDaS).
- The normal is estimated with [OmniData](https://github.com/EPFL-VILAB/omnidata), and [authors' fork](https://github.com/zhihao-lin/omnidata) can handle image resolution in a more flexible manner.
- The shadow mask is estimated with [MTMT](https://github.com/eraserNut/MTMT), and [authors' fork](https://github.com/zhihao-lin/MTMT) provides example script.
- The semantic map is estimated with [mmsegmentation](https://github.com/open-mmlab/mmsegmentation), and you could put mmseg/run.py in the root folder of [mmsegmentation](https://github.com/open-mmlab/mmsegmentation) and run.

Please let me know if you need further instructions for specific step.
