### ISSUE TITLE
Crashed by some values' percision changing to fp16 while training

### ISSUE THREAD

**Issue by RobotiX101** [zhihao-lin/urbanir#2]
some values' precision would change to fp16 while training, and lead to an unexpected crash.

**Comment by zhihao-lin** [comment]
I guess it's an issue about the **tiny-cuda-nn** package. Please follow the installation instruction in the readme. Specifically, please edit tiny-cuda-nn/include/tiny-cuda-nn/common.h and set TCNN_HALF_PRECISION to 0 (see https://github.com/NVlabs/tiny-cuda-nn/issues/51 for details)

**Comment by RobotiX101** [comment]
> I guess it's an issue about the **tiny-cuda-nn** package. Please follow the installation instruction in the readme. Specifically, please edit tiny-cuda-nn/include/tiny-cuda-nn/common.h and set TCNN_HALF_PRECISION to 0 (see [NVlabs/tiny-cuda-nn#51](https://github.com/NVlabs/tiny-cuda-nn/issues/51) for details)

thank u, solved
